---

- name: Check if MySQL already installed
  ansible.builtin.shell: rpm -qa | egrep '^mariadb-10' | wc -l
  register: mysql_installed
  changed_when: false

- name: Ensure MySQL packages are installed.
  ansible.builtin.shell: amazon-linux-extras install -y mariadb10.5
  register: rh_mysql_install_packages
  when: mysql_installed.stdout == '0'

- name: Ensure related packages are installed.
  yum:
    name: "{{ mysql_packages }}"
    state: present
    enablerepo: "{{ mysql_enablerepo | default(omit, true) }}"
  register: rh_mysql_install_packages
